# Generated by Django 3.2.6 on 2021-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
