# Generated by Django 3.2.6 on 2021-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_tugas_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
